---
platform: linux

resource_types:
- name: concourse-pipeline
  type: docker-image
  source:
    repository: concourse/concourse-pipeline-resource

resources:
- name: concourse-pipeline
  type: concourse-pipeline
  source:
    target: ((concourse_url))
    teams:
    - name: ((concourse_team))
      username: ((concourse_username))
      password: ((concourse_password))

- name: ci-config
  type: git
  source:
    branch: ((git_branch))
    uri: ((git_pipeline_url))
    private_key: ((git_key))
    git_crypt_key: ((git_crypt_key))

- name: src
  type: git
  source:
    uri: ((git_url))
    branch: ((git_branch))
    private_key: ((git_key))

- name: src-workspace
  type: git
  source:
    uri: ((git_url))
    branch: workspace
    private_key: ((git_key))

- name: gh-pages
  type: git
  source:
    uri: ((git_pages_url))
    branch: gh-pages
    private_key: ((git_pages_key))

#############################
# JOBS
#############################
jobs:

#############################
# Update Pipeline
#############################
- name: update-pipeline
  plan:
  - get: ci-config
    trigger: true
  - put: concourse-pipeline
    params:
      pipelines:
      - name: ((concourse_pipeline))
        team: ((concourse_team))
        config_file: ci-config/pipeline.yml
        vars_files:
        - ci-config/credentials.yml

#############################
### Build-test
#############################
- name: build-workspace
  plan:
  - get: src-workspace
    trigger: true
    params:
      repository: workspace
      submodules: all
      submodule_recursive: true
  - task: build_workspace_docs
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: nightwire/docker-mkdocs
          tag: latest
      inputs:
        - name: src-workspace
      run:
        path: sh
        args:
        - -exc
        - |
          cd ./src-workspace
          mkdocs build -c



#############################
### Deployment
#############################
- name: build
  plan:
  - get: src
    trigger: true
    params:
      submodules: all
      submodule_recursive: true
  - task: build_docs
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: nightwire/docker-mkdocs
          tag: latest
      inputs:
        - name: src
      run:
        path: sh
        args:
        - -exc
        - |
          cd ./src
          mkdocs build -c
      outputs:
      - name: docs
        path: ./site/
  - put: gh-pages
    params:
      repository: docs